[en]
  title = "gictor.ir"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  navbardir = "ltr"

[fa]
  title = "gictor.ir"
  languageName = "Farsi"
  weight = 2
  languagedir = "rtl"
  navbardir = "ltr"
