[[main]]
  identifier = "posts"
  name = "پست ها"
  url = "posts"
  weight = 6

[[main]]
  identifier = "archive"
  name = "آرشیو"
  url = "archive"
  weight = 5

[[main]]
  identifier = "tutorial"
  name = "آموزش"
  url = "tutorial"
  weight = 2


[[main]]
  identifier = "about"
  name = "درباره"
  url = "about"
  weight = 1

[[main]]
  identifier = "categories"
  name = "دسته بندی ها"
  url = "categories"
  weight = 4

[[main]]
  identifier = "showcase"
  name = "پروژه ها"
  url = "showcase"
  weight = 3




